import os

# Base directory of the bot.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))

ANIME_ROOM = 'animeandmanga'
GACHA_ROOM = 'gacha'
LEAGUE_ROOM = 'leagueoflegends'
SCHOL_ROOM = 'scholastic'
SPORTS_ROOM = 'sports'
TCG_ROOM = 'tcgtabletop'
VG_ROOM = 'videogames'
PEARY_ROOM = 'bikinibottom'

MAX_FRIENDS = 100

SIMPLE_COMMANDS = ['help', 'dab', 'owo', 'google', 'joogle', 'bing', 'jing', 'jibun']
UHTML_COMMANDS = ['plebs', 'calendar', 'birthday', 'anime', 'manga', 'randanime', 'randmanga']

TIMER_USER = 'T*'

JIKAN_API = 'https://api.jikan.moe/v3/'
JIKAN_SEARCH_API = 'https://api.jikan.moe/v3/search/'
DEX_API = 'https://api.mangadex.org/'
ANILIST_API = 'https://graphql.anilist.co/'
DDRAGON_API = 'http://ddragon.leagueoflegends.com/cdn/11.14.1/data/en_US/'
DDRAGON_IMG = 'http://ddragon.leagueoflegends.com/cdn/11.14.1/img/'
DDRAGON_SPL = 'http://ddragon.leagueoflegends.com/cdn/img/champion/loading/'
STEAM_API = 'http://api.steampowered.com/'
IGDB_API = 'https://api.igdb.com/v4/'
PASTIE_API = 'https://pastie.io/documents'
OPENTDB_API = 'https://opentdb.com/api.php'

MTG_API = 'https://api.scryfall.com/cards/search?q='
PTCG_API = 'https://api.pokemontcg.io/v2/cards?q=name:'
YGO_API = 'https://db.ygoprodeck.com/api/v7/cardinfo.php?fname='

BANLISTFILE = os.path.join(BASE_DIR, 'data/banlist.json')
BIRTHDAYFILE = os.path.join(BASE_DIR, 'data/birthdays.json')
CALENDARFILE = os.path.join(BASE_DIR, 'data/calendar.json')
EMOTEFILE = os.path.join(BASE_DIR, 'data/emotes.json')
FRIENDFILE = os.path.join(BASE_DIR, 'data/friends.json')
SENTENCEFILE = os.path.join(BASE_DIR, 'data/sentences.txt')
SONGFILE = os.path.join(BASE_DIR, 'data/songs.json')
SUCKFILE = os.path.join(BASE_DIR, 'data/suck.txt')
TOPICFILE = os.path.join(BASE_DIR, 'data/topics.json')
WPMFILE = os.path.join(BASE_DIR, 'data/wpm.txt')

MALFILE = os.path.join(BASE_DIR, 'data/mal.txt')
STEAMFILE = os.path.join(BASE_DIR, 'data/steam.txt')

GACHAINFOFILE = os.path.join(BASE_DIR, 'data/gacha/gacha.json')
GACHADBFILE = os.path.join(BASE_DIR, 'data/gacha/gachas.db')

MAL_URL = 'https://myanimelist.net/'
MAL_IMG_URL = 'https://cdn.myanimelist.net/images/'

IMG_NOT_FOUND = 'https://i.imgur.com/Mlw966x.png'
BLANK_IMG = 'https://i.imgur.com/skY68qe.png'
PLEB_URL = 'https://i.imgur.com/c9nyFqJ.png'

METRONOME_BATTLE = 'gen8metronomebattle'

OWNER = 'hippopotas'

GACHAS = ['fgo']

LEAGUE_CATS = ['skins', 'spells', 'items']

MAL_GENRES = {'action': 1,
              'adventure': 2,
              'cars': 3,
              'comedy': 4,
              'dementia': 5,
              'demons': 6,
              'mystery': 7,
              'drama': 8,
              'ecchi': 9,
              'fantasy': 10,
              'game': 11,
              'historical': 13,
              'horror': 14,
              'kids': 15,
              'magic': 16,
              'martialarts': 17,
              'mecha': 18,
              'music': 19,
              'parody': 20,
              'samurai': 21,
              'romance': 22,
              'school': 23,
              'scifi': 24,
              'shoujo': 25,
              'shoujoai': 26,
              'shounen': 27,
              'shounenai': 28,
              'space': 29,
              'sports': 30,
              'superpower': 31,
              'vampire': 32,
              'yaoi': 33,
              'yuri': 34,
              'harem': 35,
              'sliceoflife': 36,
              'supernatural': 37,
              'military': 38,
              'police': 39,
              'psychological':40}

ANIME_GENRES = {**MAL_GENRES, 'thriller': 41, 'seinen': 42, 'josei': 43}
MANGA_GENRES = {**MAL_GENRES, 'seinen': 41, 'josei': 42, 'genderbender': 44, 'thriller': 45}

ANIME_TYPES = ['anime', 'tv', 'ova', 'movie', 'special', 'ona', 'music']
MANGA_TYPES = ['manga', 'novel', 'oneshot', 'manhwa', 'manhua']

VG_GENRES = ['fighting',
             'shooter',
             'music',
             'platform',
             'puzzle',
             'racing',
             'real-time-strategy-rts',
             'role-playing-rpg',
             'simulator',
             'sport',
             'strategy',
             'turn-based-strategy-tbs',
             'tactical',
             'quiz-trivia',
             'hack-and-slash-beat-em-up',
             'pinball',
             'adventure',
             'arcade',
             'visual-novel',
             'indie',
             'card-and-board-game',
             'moba',
             'point-and-click']

VG_THEMES = ['thriller',
             'science-fiction',
             'action',
             'horror',
             'survival',
             'fantasy',
             'historical',
             'stealth',
             'comedy',
             'business',
             'drama',
             'non-fiction',
             'kids',
             'sandbox',
             'open-world',
             'warfare',
             '4x-explore-expand-exploit-and-exterminate',
             'educational',
             'mystery',
             'party',
             'romance']

ANILIST_MEDIA = ['TV',
                 'TV_SHORT',
                 'MOVIE',
                 'SPECIAL',
                 'OVA',
                 'ONA',
                 'MANGA',
                 'NOVEL',
                 'ONE_SHOT']

ANILIST_GENRES = ["Action",
                  "Adventure",
                  "Comedy",
                  "Drama",
                  "Ecchi",
                  "Fantasy",
                  "Horror",
                  "Mahou Shoujo",
                  "Mecha",
                  "Music",
                  "Mystery",
                  "Psychological",
                  "Romance",
                  "Sci-Fi",
                  "Slice of Life",
                  "Sports",
                  "Supernatural",
                  "Thriller"]

ANILIST_TAGS = {'4-koma': 206,
                'Achromatic': 710,
                'Achronological Order': 156,
                'Acting': 548,
                'Adoption': 1052,
                'Advertisement': 505,
                'Afterlife': 147,
                'Age Gap': 138,
                'Age Regression': 488,
                'Agender': 334,
                'Agriculture': 909,
                'Airsoft': 167,
                'Aliens': 191,
                'Alternate Universe': 146,
                'American Football': 314,
                'Amnesia': 240,
                'Anachronism': 490,
                'Angels': 1068,
                'Animals': 433,
                'Anthology': 471,
                'Anti-Hero': 104,
                'Archery': 251,
                'Artificial Intelligence': 517,
                'Asexual': 622,
                'Assassins': 322,
                'Astronomy': 623,
                'Athletics': 264,
                'Augmented Reality': 364,
                'Autobiographical': 519,
                'Aviation': 355,
                'Badminton': 235,
                'Band': 110,
                'Bar': 161,
                'Baseball': 149,
                'Basketball': 192,
                'Battle Royale': 101,
                'Biographical': 239,
                'Bisexual': 294,
                'Body Swapping': 154,
                'Boxing': 169,
                "Boys' Love": 75,
                'Bullying': 171,
                'Butler': 812,
                'Calligraphy': 204,
                'Card Battle': 178,
                'Cars': 10,
                'Centaur': 632,
                'CGI': 90,
                'Cheerleading': 646,
                'Chibi': 324,
                'Chimera': 774,
                'Chuunibyou': 267,
                'Circus': 476,
                'Classic Literature': 227,
                'College': 404,
                'Coming of Age': 102,
                'Conspiracy': 456,
                'Cosmic Horror': 636,
                'Cosplay': 328,
                'Crime': 648,
                'Crossdressing': 186,
                'Crossover': 158,
                'Cult': 586,
                'Cultivation': 326,
                'Cute Boys Doing Cute Things': 1063,
                'Cute Girls Doing Cute Things': 92,
                'Cyberpunk': 108,
                'Cyborg': 801,
                'Cycling': 151,
                'Dancing': 209,
                'Death Game': 615,
                'Delinquents': 395,
                'Demons': 15,
                'Denpa': 654,
                'Detective': 694,
                'Dinosaurs': 704,
                'Dissociative Identities': 536,
                'Dragons': 224,
                'Drawing': 118,
                'Dullahan': 658,
                'Dungeon': 604,
                'Dystopian': 217,
                'E-Sports': 792,
                'Economics': 248,
                'Educational': 140,
                'Elf': 598,
                'Ensemble Cast': 105,
                'Environmental': 342,
                'Episodic': 193,
                'Espionage': 310,
                'Fairy Tale': 400,
                'Family Life': 87,
                'Fashion': 410,
                'Female Harem': 23,
                'Female Protagonist': 98,
                'Fencing': 1132,
                'Firefighters': 613,
                'Fishing': 212,
                'Fitness': 170,
                'Flash': 242,
                'Food': 142,
                'Football': 148,
                'Foreign': 198,
                'Fugitive': 226,
                'Full CGI': 89,
                'Full Color': 207,
                'Gambling': 91,
                'Gangs': 106,
                'Gender Bending': 77,
                'Ghost': 220,
                'Go': 443,
                'Goblin': 480,
                'Gods': 253,
                'Golf': 532,
                'Guns': 157,
                'Gyaru': 356,
                'Henshin': 99,
                'Heterosexual': 1045,
                'Hikikomori': 282,
                'Historical': 25,
                'Ice Skating': 228,
                'Idol': 115,
                'Isekai': 244,
                'Iyashikei': 81,
                'Josei': 27,
                'Judo': 1105,
                'Kaiju': 276,
                'Karuta': 182,
                'Kemonomimi': 254,
                'Kids': 28,
                'Kuudere': 779,
                'Lacrosse': 437,
                'Language Barrier': 516,
                'LGBTQ+ Themes': 483,
                'Lost Civilization': 466,
                'Love Triangle': 139,
                'Mafia': 107,
                'Magic': 29,
                'Mahjong': 117,
                'Maids': 249,
                'Make-up': 1140,
                'Male Harem': 123,
                'Male Protagonist': 82,
                'Martial Arts': 30,
                'Medicine': 659,
                'Memory Manipulation': 365,
                'Mermaid': 558,
                'Meta': 144,
                'Military': 34,
                'Monster Boy': 1090,
                'Monster Girl': 259,
                'Mopeds': 176,
                'Motorcycles': 173,
                'Musical': 265,
                'Mythology': 208,
                'Nekomimi': 113,
                'Ninja': 255,
                'No Dialogue': 341,
                'Noir': 327,
                'Nun': 614,
                'Office Lady': 653,
                'Ojou-sama': 780,
                'Otaku Culture': 97,
                'Outdoor': 262,
                'Pandemic': 874,
                'Parkour': 949,
                'Parody': 39,
                'Philosophy': 391,
                'Photography': 195,
                'Pirates': 201,
                'Poker': 183,
                'Police': 40,
                'Politics': 103,
                'Post-Apocalyptic': 93,
                'POV': 215,
                'Primarily Adult Cast': 109,
                'Primarily Child Cast': 446,
                'Primarily Female Cast': 86,
                'Primarily Male Cast': 88,
                'Puppetry': 325,
                'Rakugo': 481,
                'Real Robot': 160,
                'Rehabilitation': 311,
                'Reincarnation': 243,
                'Religion': 1091,
                'Revenge': 252,
                'Robots': 175,
                'Rotoscoping': 683,
                'Rugby': 221,
                'Rural': 250,
                'Samurai': 291,
                'Satire': 80,
                'School': 46,
                'School Club': 84,
                'Scuba Diving': 811,
                'Seinen': 50,
                'Shapeshifting': 772,
                'Ships': 305,
                'Shogi': 121,
                'Shoujo': 53,
                'Shounen': 56,
                'Shrine Maiden': 468,
                'Skateboarding': 809,
                'Skeleton': 499,
                'Slapstick': 83,
                'Slavery': 247,
                'Software Development': 386,
                'Space': 63,
                'Space Opera': 162,
                'Steampunk': 95,
                'Stop Motion': 323,
                'Succubus': 665,
                'Sumo': 1080,
                'Super Power': 66,
                'Super Robot': 159,
                'Superhero': 172,
                'Surfing': 678,
                'Surreal Comedy': 281,
                'Survival': 143,
                'Swimming': 150,
                'Swordplay': 43,
                'Table Tennis': 120,
                'Tanks': 174,
                'Tanned Skin': 335,
                'Teacher': 165,
                "Teens' Love": 649,
                'Tennis': 194,
                'Terrorism': 285,
                'Time Manipulation': 96,
                'Time Skip': 153,
                'Tokusatsu': 513,
                'Tomboy': 931,
                'Torture': 1121,
                'Tragedy': 85,
                'Trains': 122,
                'Triads': 214,
                'Tsundere': 164,
                'Twins': 494,
                'Urban': 595,
                'Urban Fantasy': 321,
                'Vampire': 74,
                'Video Games': 308,
                'Vikings': 618,
                'Villainess': 857,
                'Virtual World': 112,
                'Volleyball': 116,
                'VTuber': 1047,
                'War': 111,
                'Werewolf': 534,
                'Witch': 179,
                'Work': 145,
                'Wrestling': 231,
                'Writing': 394,
                'Wuxia': 303,
                'Yakuza': 199,
                'Yandere': 163,
                'Youkai': 233,
                'Yuri': 76,
                'Zombie': 152}

MAL_LAST_PAGES = {
    "anime": {
        "anime": {
            "action": 81,
            "adventure": 62,
            "cars": 3,
            "comedy": 125,
            "dementia": 11,
            "demons": 11,
            "mystery": 15,
            "drama": 54,
            "ecchi": 16,
            "fantasy": 69,
            "game": 9,
            "historical": 24,
            "horror": 10,
            "kids": 61,
            "magic": 23,
            "martialarts": 10,
            "mecha": 23,
            "music": 48,
            "parody": 14,
            "samurai": 5,
            "romance": 39,
            "school": 34,
            "scifi": 54,
            "shoujo": 14,
            "shoujoai": 2,
            "shounen": 40,
            "shounenai": 3,
            "space": 11,
            "sports": 15,
            "superpower": 13,
            "vampire": 3,
            "yaoi": 1,
            "yuri": 1,
            "harem": 9,
            "sliceoflife": 40,
            "supernatural": 31,
            "military": 12,
            "police": 6,
            "psychological": 8,
            "thriller": 3,
            "seinen": 17,
            "josei": 2,
            "": 367
        },
        "tv": {
            "action": 30,
            "adventure": 25,
            "cars": 2,
            "comedy": 50,
            "dementia": 1,
            "demons": 4,
            "mystery": 7,
            "drama": 19,
            "ecchi": 7,
            "fantasy": 23,
            "game": 4,
            "historical": 8,
            "horror": 3,
            "kids": 21,
            "magic": 10,
            "martialarts": 3,
            "mecha": 9,
            "music": 5,
            "parody": 4,
            "samurai": 2,
            "romance": 17,
            "school": 16,
            "scifi": 20,
            "shoujo": 7,
            "shoujoai": 1,
            "shounen": 18,
            "shounenai": 1,
            "space": 4,
            "sports": 7,
            "superpower": 5,
            "vampire": 2,
            "yaoi": -1,
            "yuri": -1,
            "harem": 5,
            "sliceoflife": 18,
            "supernatural": 12,
            "military": 4,
            "police": 2,
            "psychological": 3,
            "thriller": 2,
            "seinen": 8,
            "josei": 2,
            "": 107
        },
        "ova": {
            "action": 15,
            "adventure": 9,
            "cars": 1,
            "comedy": 19,
            "dementia": 1,
            "demons": 4,
            "mystery": 3,
            "drama": 13,
            "ecchi": 5,
            "fantasy": 13,
            "game": 1,
            "historical": 4,
            "horror": 3,
            "kids": 12,
            "magic": 5,
            "martialarts": 2,
            "mecha": 6,
            "music": 2,
            "parody": 3,
            "samurai": 1,
            "romance": 10,
            "school": 7,
            "scifi": 12,
            "shoujo": 3,
            "shoujoai": 1,
            "shounen": 8,
            "shounenai": 1,
            "space": 3,
            "sports": 3,
            "superpower": 3,
            "vampire": 1,
            "yaoi": 1,
            "yuri": 1,
            "harem": 3,
            "sliceoflife": 4,
            "supernatural": 7,
            "military": 3,
            "police": 2,
            "psychological": 2,
            "thriller": 1,
            "seinen": 4,
            "josei": 1,
            "": 79
        },
        "movie": {
            "action": 16,
            "adventure": 16,
            "cars": 1,
            "comedy": 18,
            "dementia": 7,
            "demons": 2,
            "mystery": 3,
            "drama": 14,
            "ecchi": 1,
            "fantasy": 16,
            "game": 1,
            "historical": 6,
            "horror": 2,
            "kids": 12,
            "magic": 4,
            "martialarts": 2,
            "mecha": 5,
            "music": 4,
            "parody": 2,
            "samurai": 1,
            "romance": 5,
            "school": 3,
            "scifi": 11,
            "shoujo": 3,
            "shoujoai": 1,
            "shounen": 8,
            "shounenai": 1,
            "space": 3,
            "sports": 3,
            "superpower": 3,
            "vampire": 1,
            "yaoi": 1,
            "yuri": -1,
            "harem": 1,
            "sliceoflife": 5,
            "supernatural": 5,
            "military": 4,
            "police": 2,
            "psychological": 2,
            "thriller": 1,
            "seinen": 3,
            "josei": 1,
            "": 64
        },
        "special": {
            "action": 10,
            "adventure": 8,
            "cars": 1,
            "comedy": 23,
            "dementia": 1,
            "demons": 2,
            "mystery": 3,
            "drama": 6,
            "ecchi": 4,
            "fantasy": 8,
            "game": 2,
            "historical": 3,
            "horror": 1,
            "kids": 4,
            "magic": 3,
            "martialarts": 1,
            "mecha": 3,
            "music": 3,
            "parody": 4,
            "samurai": 1,
            "romance": 5,
            "school": 6,
            "scifi": 7,
            "shoujo": 2,
            "shoujoai": 1,
            "shounen": 6,
            "shounenai": 1,
            "space": 2,
            "sports": 3,
            "superpower": 2,
            "vampire": 1,
            "yaoi": 1,
            "yuri": -1,
            "harem": 1,
            "sliceoflife": 7,
            "supernatural": 4,
            "military": 2,
            "police": 1,
            "psychological": 1,
            "thriller": 1,
            "seinen": 3,
            "josei": 1,
            "": 46
        },
        "ona": {
            "action": 10,
            "adventure": 5,
            "cars": 1,
            "comedy": 16,
            "dementia": 2,
            "demons": 2,
            "mystery": 2,
            "drama": 4,
            "ecchi": 1,
            "fantasy": 10,
            "game": 2,
            "historical": 4,
            "horror": 2,
            "kids": 4,
            "magic": 2,
            "martialarts": 3,
            "mecha": 2,
            "music": 4,
            "parody": 4,
            "samurai": 1,
            "romance": 4,
            "school": 3,
            "scifi": 5,
            "shoujo": 1,
            "shoujoai": 1,
            "shounen": 2,
            "shounenai": 1,
            "space": 1,
            "sports": 1,
            "superpower": 1,
            "vampire": 1,
            "yaoi": 1,
            "yuri": -1,
            "harem": 1,
            "sliceoflife": 7,
            "supernatural": 4,
            "military": 1,
            "police": 1,
            "psychological": 1,
            "thriller": 1,
            "seinen": 1,
            "josei": 1,
            "": 42
        },
        "music": {
            "action": 1,
            "adventure": 1,
            "cars": 1,
            "comedy": 1,
            "dementia": 2,
            "demons": 1,
            "mystery": 1,
            "drama": 2,
            "ecchi": 1,
            "fantasy": 2,
            "game": 1,
            "historical": 1,
            "horror": 1,
            "kids": 10,
            "magic": 1,
            "martialarts": -1,
            "mecha": 1,
            "music": 31,
            "parody": 1,
            "samurai": 1,
            "romance": 1,
            "school": 1,
            "scifi": 1,
            "shoujo": 1,
            "shoujoai": -1,
            "shounen": -1,
            "shounenai": -1,
            "space": 1,
            "sports": 1,
            "superpower": 1,
            "vampire": 1,
            "yaoi": -1,
            "yuri": -1,
            "harem": 1,
            "sliceoflife": 1,
            "supernatural": 1,
            "military": 1,
            "police": 1,
            "psychological": 1,
            "thriller": -1,
            "seinen": 1,
            "josei": -1,
            "": 31
        },
        "": {
            "action": 81,
            "adventure": 62,
            "cars": 3,
            "comedy": 125,
            "dementia": 11,
            "demons": 11,
            "mystery": 15,
            "drama": 54,
            "ecchi": 16,
            "fantasy": 69,
            "game": 9,
            "historical": 24,
            "horror": 10,
            "kids": 61,
            "magic": 23,
            "martialarts": 10,
            "mecha": 23,
            "music": 48,
            "parody": 14,
            "samurai": 5,
            "romance": 39,
            "school": 34,
            "scifi": 54,
            "shoujo": 14,
            "shoujoai": 2,
            "shounen": 40,
            "shounenai": 3,
            "space": 11,
            "sports": 15,
            "superpower": 13,
            "vampire": 3,
            "yaoi": 1,
            "yuri": 1,
            "harem": 9,
            "sliceoflife": 40,
            "supernatural": 31,
            "military": 12,
            "police": 6,
            "psychological": 8,
            "thriller": 3,
            "seinen": 17,
            "josei": 2,
            "": 367
        }
    },
    "manga": {
        "manga": {
            "action": 102,
            "adventure": 48,
            "cars": 2,
            "comedy": 196,
            "dementia": 2,
            "demons": 10,
            "mystery": 34,
            "drama": 132,
            "ecchi": 54,
            "fantasy": 98,
            "game": 6,
            "historical": 36,
            "horror": 26,
            "kids": 5,
            "magic": 16,
            "martialarts": 10,
            "mecha": 11,
            "music": 7,
            "parody": 6,
            "samurai": 4,
            "romance": 203,
            "school": 133,
            "scifi": 44,
            "shoujo": 128,
            "shoujoai": 13,
            "shounen": 93,
            "shounenai": 23,
            "space": 4,
            "sports": 20,
            "superpower": 8,
            "vampire": 6,
            "yaoi": 114,
            "yuri": 8,
            "harem": 18,
            "sliceoflife": 85,
            "supernatural": 86,
            "military": 10,
            "police": 6,
            "psychological": 21,
            "seinen": 127,
            "josei": 42,
            "genderbender": 17,
            "thriller": 5,
            "": 771
        },
        "novel": {
            "action": 37,
            "adventure": 15,
            "cars": -1,
            "comedy": 35,
            "dementia": 1,
            "demons": 2,
            "mystery": 7,
            "drama": 16,
            "ecchi": 15,
            "fantasy": 61,
            "game": 2,
            "historical": 2,
            "horror": 3,
            "kids": -1,
            "magic": 7,
            "martialarts": 1,
            "mecha": 3,
            "music": 1,
            "parody": 1,
            "samurai": 1,
            "romance": 67,
            "school": 38,
            "scifi": 12,
            "shoujo": 5,
            "shoujoai": 1,
            "shounen": 3,
            "shounenai": 1,
            "space": 1,
            "sports": 1,
            "superpower": 3,
            "vampire": 2,
            "yaoi": 4,
            "yuri": 1,
            "harem": 26,
            "sliceoflife": 5,
            "supernatural": 31,
            "military": 3,
            "police": 1,
            "psychological": 3,
            "seinen": 1,
            "josei": 27,
            "genderbender": 3,
            "thriller": 1,
            "": 197
        },
        "oneshot": {
            "action": 7,
            "adventure": 2,
            "cars": 1,
            "comedy": 15,
            "dementia": 1,
            "demons": 1,
            "mystery": 2,
            "drama": 9,
            "ecchi": 4,
            "fantasy": 6,
            "game": 1,
            "historical": 2,
            "horror": 3,
            "kids": 1,
            "magic": 1,
            "martialarts": 1,
            "mecha": 1,
            "music": 1,
            "parody": 1,
            "samurai": 1,
            "romance": 18,
            "school": 13,
            "scifi": 3,
            "shoujo": 15,
            "shoujoai": 3,
            "shounen": 13,
            "shounenai": 3,
            "space": 1,
            "sports": 2,
            "superpower": 1,
            "vampire": 1,
            "yaoi": 6,
            "yuri": 2,
            "harem": 1,
            "sliceoflife": 5,
            "supernatural": 10,
            "military": 1,
            "police": 1,
            "psychological": 2,
            "seinen": 8,
            "josei": 2,
            "genderbender": 3,
            "thriller": 1,
            "": 93
        },
        "manhwa": {
            "action": 5,
            "adventure": 3,
            "cars": -1,
            "comedy": 8,
            "dementia": 1,
            "demons": 1,
            "mystery": 2,
            "drama": 8,
            "ecchi": 1,
            "fantasy": 6,
            "game": 1,
            "historical": 2,
            "horror": 1,
            "kids": 1,
            "magic": 1,
            "martialarts": 2,
            "mecha": 1,
            "music": 1,
            "parody": 1,
            "samurai": -1,
            "romance": 11,
            "school": 4,
            "scifi": 2,
            "shoujo": 8,
            "shoujoai": 1,
            "shounen": 2,
            "shounenai": 1,
            "space": 1,
            "sports": 1,
            "superpower": 1,
            "vampire": 1,
            "yaoi": 1,
            "yuri": 1,
            "harem": 1,
            "sliceoflife": 3,
            "supernatural": 3,
            "military": 1,
            "police": 1,
            "psychological": 2,
            "seinen": 1,
            "josei": 1,
            "genderbender": 1,
            "thriller": 1,
            "": 21
        },
        "manhua": {
            "action": 2,
            "adventure": 2,
            "cars": 1,
            "comedy": 2,
            "dementia": -1,
            "demons": 1,
            "mystery": 1,
            "drama": 2,
            "ecchi": 1,
            "fantasy": 3,
            "game": 1,
            "historical": 2,
            "horror": 1,
            "kids": 1,
            "magic": 1,
            "martialarts": 1,
            "mecha": 1,
            "music": 1,
            "parody": -1,
            "samurai": -1,
            "romance": 3,
            "school": 1,
            "scifi": 1,
            "shoujo": 2,
            "shoujoai": 1,
            "shounen": 1,
            "shounenai": 1,
            "space": -1,
            "sports": 1,
            "superpower": 1,
            "vampire": 1,
            "yaoi": 1,
            "yuri": -1,
            "harem": 1,
            "sliceoflife": 1,
            "supernatural": 1,
            "military": 1,
            "police": 1,
            "psychological": 1,
            "seinen": 1,
            "josei": 1,
            "genderbender": 1,
            "thriller": -1,
            "": 6
        },
        "": {
            "action": 153,
            "adventure": 68,
            "cars": 2,
            "comedy": 257,
            "dementia": 3,
            "demons": 14,
            "mystery": 44,
            "drama": 167,
            "ecchi": 73,
            "fantasy": 174,
            "game": 9,
            "historical": 43,
            "horror": 32,
            "kids": 5,
            "magic": 23,
            "martialarts": 13,
            "mecha": 14,
            "music": 9,
            "parody": 6,
            "samurai": 5,
            "romance": 302,
            "school": 191,
            "scifi": 60,
            "shoujo": 156,
            "shoujoai": 18,
            "shounen": 110,
            "shounenai": 28,
            "space": 5,
            "sports": 23,
            "superpower": 12,
            "vampire": 9,
            "yaoi": 133,
            "yuri": 12,
            "harem": 44,
            "sliceoflife": 98,
            "supernatural": 132,
            "military": 13,
            "police": 7,
            "psychological": 26,
            "seinen": 137,
            "josei": 71,
            "genderbender": 27,
            "thriller": 6,
            "": 1118
        }
    }
}
